apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: church-auth
  name: church-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: church-auth
  strategy: {}
  template:
    metadata:
      labels:
        app: church-auth
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: -XX:+UseSerialGC -Xss512k -XX:MaxRAM=72m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATABASE_HOST
              value: mysql
            - name: SPRING_DATABASE_PORT
              value: "3306"
          image: churchsource/church-auth
          name: church-auth
      restartPolicy: Always
status: {}
