apiVersion: v1
kind: Service
{{ $chart := .Chart }}
metadata:
  name: {{ $chart.Name | quote }}
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 81
      protocol: TCP
      targetPort: 81
  selector:
    app: {{ $chart.Name }}