apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: External
  name: church-gateway-service
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: church-gateway
