apiVersion: v1
kind: Service
metadata:
  name: church-people-frontend
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: ClusterIP
  ports:
    - port: 81
      protocol: TCP
      targetPort: 81
  selector:
    app: church-people-frontend