apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: church-people-data
  name: church-people-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000Mi
status: {}
